"""Initial migration

Revision ID: 37d108c7a37c
Revises: 
Create Date: 2026-05-05 13:54:48.646297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d108c7a37c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hcp_name', sa.String(length=255), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('attendees', sa.String(length=512), nullable=True),
    sa.Column('topics_discussed', sa.Text(), nullable=True),
    sa.Column('materials_shared', sa.Text(), nullable=True),
    sa.Column('samples_distributed', sa.Text(), nullable=True),
    sa.Column('hcp_sentiment', sa.String(length=50), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.Text(), nullable=True),
    sa.Column('ai_suggested_followups', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
